# Generated by Django 4.2 on 2023-06-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_comment_downvotes_alter_comment_upvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=80)),
                ('comment_count', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='company',
        ),
        migrations.AddField(
            model_name='comment',
            name='company_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.company'),
        ),
    ]
